### ISSUE TITLE
No instructions

### ISSUE THREAD

**Issue by aso595** [lennonhill/cookies-txt#13]
There are no instructions in the README explaining how to actually export the cookies.
Firefox 91.0.1
Nothing in the menus.
No icon in the tool bar. Checked for a missing icon in 'customise toolbar' - nothing
Looked in preferences for cookies. Nothing but the standard options
Looked in the cookies dialog in preferences where you can clear cookies etc. Nothing there either.

**Comment by ctb** [comment]
I ran into the same problem, finally figured it out - it adds an icon on the upper right that looks like a cookie jar. You can verify it's the right icon by right-clicking and then selecting "manage extension", which will bring you to the extension management page for this extension.

See https://github.com/lennonhill/cookies-txt/blob/master/icons/icon-128.png for the icon itself.

**Comment by lennonhill** [comment]
Fixed in 1cebb7de27fd9f184758aabdd49a48dd126fb69e.
