### ISSUE TITLE
Shortcut does not show up in the toolbar or menu

### ISSUE THREAD

**Issue by Bum-Cement** [lennonhill/cookies-txt#16]
The cookies-txt extension has no visible shortcut to export cookies. It's not in any of the menus either, but it does show up as installed. When I try to configure extension shortcuts the settings options for it say that there are no shortcuts available for this extension. Tried restarting the browser, tried rebooting the PC. 

Firefox 98.0 (64-bit)

Operating System: openSUSE Tumbleweed 20220314
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.2
Kernel Version: 5.16.14-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-2400 CPU @ 3.10GHz
Memory: 7.7 GiB of RAM
Graphics Processor: AMD OLAND

Issue also appears in Windows 10 Pro Firefox ver. 98.0.1 (64-bit)

![Screenshot_20220321_173216](https://user-images.githubusercontent.com/88676245/159385065-58b87f2b-4031-40f5-a0a8-1eb5de723c52.png)

Attachment: [hardinfo_report.zip](https://github.com/lennonhill/cookies-txt/files/8319979/hardinfo_report.zip)

**Comment by luni3359** [comment]
Did you try looking in the `>>` menu, or in the Customize toolbar page?

**Comment by Bum-Cement** [comment]
> Did you try looking in the `>>` menu, or in the Customize toolbar page?

Yes.

**Comment by hrdl-github** [comment]
I cannot reproduce this behaviour.

**Comment by Bum-Cement** [comment]
This doesn't seem to be an issue anymore in Firefox ver. 104.0.2 (64-bit) on openSUSE Leap 15.4. Surely it's also working again in Tumbleweed. I will close this. Sorry if you went through the effort of trying to replicate this on openSUSE Tumbleweed.
