### ISSUE TITLE
Unclear how to export cookies

### ISSUE THREAD

**Issue by RickNak** [lennonhill/cookies-txt#2]
I was thinking I would find a new entry under the Tools menu item ("Export cookies"), but it's not there.  How do you use this add-in to export your cookies?

**Comment by E3V3A** [comment]
YEah dude how the hell do you export the cookies?

**Comment by jimav** [comment]
Please add something to the add-on description which says how to use it, i.e. how to actually get a cookies.txt file (or if it is created continuously, then where is it stored?)

**Comment by RickNak** [comment]
After nearly a year and a half, I'm no longer using this software, so I'm going to close this issue.

**Comment by frou** [comment]
![Screenshot 2020-02-06 at 15 54 04 (3)](https://user-images.githubusercontent.com/172663/73954054-2f8c4580-48f9-11ea-96b3-21280e33250e.png)

The answer is that it's Firefox toolbar button, which then brings up a file-save dialog for where to save the `.txt` file.
