### ISSUE TITLE
Firefox Addons Page: Add link to this repository

### ISSUE THREAD

**Issue by vadcx** [lennonhill/cookies-txt#22]
The source code repository is only referenced in the `manifest.json` file, that link is only visible after installation in the extension's info/settings. The [Firefox Addons](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/) page does not have it on the left.

For example, [uBlockOrigin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) has their repo as the "Homepage" link and the subreddit as the "Support page".

It was very hard for me to find the repository though a search engine due to the generic name. Consider adding a backlink to Firefox Addons to the [readme.md](https://github.com/hrdl-github/cookies-txt/blob/master/README.md) here too

**Comment by hrdl-github** [comment]
Thanks, I've fixed this. There used to be a link to this repository. My best guess is that Mozilla removed it when I changed my github username.
