### ISSUE TITLE
Not working for youtube 

### ISSUE THREAD

**Issue by Yergov** [lennonhill/cookies-txt#25]
2-3 days ago i was successfully able to download a video from youtube which was for members who are paid subscriber as i am the paid subscriber but today i tried to download from same channel but video is not downloading and it keeps saying error. yesterday mozilla got updated. not sure if that is the reason. 
 i am attaching the screenshot of error thats keep showing
![Screenshot 2024-01-25 193304](https://github.com/hrdl-github/cookies-txt/assets/157714438/c7a2d8f0-c484-4bb2-9dcb-c18e2067a820)

**Comment by hrdl-github** [comment]
I don't have access to a Google account, so I cannot test this. Consider inspecting the resulting `cookies.txt` file manually. If that one looks fine then there's a chance that they introduced other mechanisms preventing scraping of media content, e.g. user-agent-based ones or shorter-lived cookies, which would have to be handled by e.g. `yt-dlp`.
