### ISSUE TITLE
Allow download for current container only

### ISSUE THREAD

**Issue by Zegnat** [lennonhill/cookies-txt#26]
Currently users are given the choice “ALL / Current Site”. When wanting to use the cookies for `curl`/`wget` I often just want to grab them for one site, within one of my containers, there is no need for more than that.

Because I use [Temporary Containers](https://github.com/stoically/temporary-containers) this problem might be extra visible to me, because I have so many containers going at all times.

Potential solution would be to add extra choices for download:
* ALL from Current Container
* Current Site from Current Container

I might have a go at a PR for this, if I run into another project where I need this add-on. Great add-on anyways 👍

**Comment by hrdl-github** [comment]
This makes a lot of sense. I don't have time to extend this add-on myself, as web development is very far away from my core skill set. Contributions are always welcome though, especially when it comes to aligning the site selection / export process more aligned with users' expectations.

**Comment by oatmeal** [comment]
@Zegnat Are you still working on this? If not I can try to take a look in the next week or so.

**edit**: I ended up having some time this evening so I hacked something together in #29.

**Comment by tw-martijn** [comment]
I was not working on this anymore, I have not had a need to repeat this (yet). Great to see a PR! 👏  I might take a look at your code later this week when time permits.

**Comment by hrdl-github** [comment]
Closed by #29.
