### ISSUE TITLE
Does not work along with another add-on: Multi-Account Containers

### ISSUE THREAD

**Issue by olspookishmagus** [lennonhill/cookies-txt#7]
Hello.

Please be aware that cookies.txt add-on does not work with another add-on namely: Multi-Account containers found here:
https://addons.mozilla.org/firefox/addon/multi-account-containers/

I will fill in more details later until then, let this be a placeholder for the relevant discussion.

Sophoklis

**Comment by lennonhill** [comment]
Solved by https://github.com/lennonhill/cookies-txt/commit/dcb5c0c1ec26664108773ffd16d78f56f949c3d2
